---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Darwinian Shortfalls

This repository contains all data, scripts and functions to the manuscript "Darwinian Shortfall in Fishes"

# Repository structure
This repository contains the full data to reproduce the analysis and figures present in the manuscript "Darwinian Shortfall in Fishes"

## Folders 

- data: contains all data needed to perform the analysis

- doc: .doc documents containing the manuscript describing the package

- output: contains all results, including figures and .rds files generated with archives contained in R folder that starts with letters D and S

- R: contains all .R scripts. Archives that starts with letter D and S are designed to, respectivelly, run analysis and generate figures for the results of these analyses.

# Downloading the repository

The user can download this repo to a local folder in your computer or clone it:

## downloading all files

`download.file(url = "https://github.com/GabrielNakamura/MS_FishPhyloMaker/archive/main.zip", destfile = "MS_DarwinianShortfallFish.zip")`

to unzip the .zip file in your computer type

`unzip(zipfile = "MS_DarwinianShortfallFish.zip")`

# Tasks 

- Use a single phylogeny
    - [ ] Modify FishPhyloMaker or use rtrees 
    
- Update figures
    - [X] Absolute Barplot for Orders 
    - [ ] Stacked barplot for Orders
    - [X] Phylogenies and insertions for Marine and Fresh
    - [ ] Single Phylogeny

- Metrics 
    - [X] Shorfalls using pseudo posterior distributions 
    - [ ] Edge for all data
    - [X] Script for EDGE
    - [X] Request API from IUCN
    - [ ] Possibility to use data from FB

